# Generated by Django 4.0.2 on 2022-05-08 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vendors',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('shop_name', models.CharField(max_length=20)),
                ('shop_address', models.CharField(max_length=100)),
                ('shop_service', models.CharField(max_length=20)),
                ('phone_no', models.IntegerField(max_length=10)),
            ],
        ),
    ]
